name: Build

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: BuildSwaggers
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: documentation
    env:
      ruby-version: 2.5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ env.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: npm install -g @apidevtools/swagger-cli

      ###
      #ATENÇÃO: não é parar ligar a automação da Fase 1 sem a autorização do comitê de Open Banking
      # Open Banking Fase 1
      #- run: swagger-cli bundle source/swagger/parts/_open_banking_fase1_apis_part.yml --outfile source/swagger/swagger_open_banking_fase1_apis.yml --type=yaml
      ###

      # Open Banking Fase 2
      - run: VERSION=$(grep 'version:' source/swagger/parts/_accounts_apis_part.yml | tail -n1 | awk '{ print $2}')
      - run: echo "${VERSION}......------"
      - run: swagger-cli bundle source/swagger/parts/_accounts_apis_part.yml --outfile build/swagger/accounts/doc/${VERSION}.json --type=json
      - run: VERSION=$(grep 'version:' source/swagger/parts/_consents_apis_part.yml | tail -n1 | awk '{ print $2}')
      - run: swagger-cli bundle source/swagger/parts/_consents_apis_part.yml --outfile build/swagger/consents/doc/${VERSION}.json --type=json
      - run: VERSION=$(grep 'version:' source/swagger/parts/_credit_cards_apis_part.yml | tail -n1 | awk '{ print $2}')
      - run: swagger-cli bundle source/swagger/parts/_credit_cards_apis_part.yml --outfile build/swagger/credit_cards/doc/${VERSION}.json --type=json
      - run: VERSION=$(grep 'version:' source/swagger/parts/_customers_apis_part.yml | tail -n1 | awk '{ print $2}')
      - run: swagger-cli bundle source/swagger/parts/_customers_apis_part.yml --outfile build/swagger/customers/doc/${VERSION}.json --type=json
      - run: VERSION=$(grep 'version:' source/swagger/parts/_financings_apis_part.yml | tail -n1 | awk '{ print $2}')
      - run: swagger-cli bundle source/swagger/parts/_financings_apis_part.yml --outfile build/swagger/financings/doc/${VERSION}.json --type=json
      - run: VERSION=$(grep 'version:' source/swagger/parts/_invoice_financings_apis_part.yml | tail -n1 | awk '{ print $2}')
      - run: swagger-cli bundle source/swagger/parts/_invoice_financings_apis_part.yml --outfile build/swagger/invoice_financings/doc/${VERSION}.json --type=json
      - run: VERSION=$(grep 'version:' source/swagger/parts/_loans_apis_part.yml | tail -n1 | awk '{ print $2}')
      - run: swagger-cli bundle source/swagger/parts/_loans_apis_part.yml --outfile build/swagger/loans/doc/${VERSION}.json --type=json
      - run: VERSION=$(grep 'version:' source/swagger/parts/_resources_apis_part.yml | tail -n1 | awk '{ print $2}')
      - run: swagger-cli bundle source/swagger/parts/_resources_apis_part.yml --outfile build/swagger/resources/doc/${VERSION}.json --type=json
      - run: VERSION=$(grep 'version:' source/swagger/parts/_unarranged_accounts_overdraft_apis_part.yml | tail -n1 | awk '{ print $2}')
      - run: swagger-cli bundle source/swagger/parts/_unarranged_accounts_overdraft_apis_part.yml --outfile build/swagger/unarranged_accounts_overdraft/doc/${VERSION}.json --type=json


      # Open Banking Fase 3
      - run: VERSION=$(grep 'version:' source/swagger/parts/_payments_apis_part.yml | tail -n1 | awk '{ print $2}')
      - run: swagger-cli bundle source/swagger/parts/_payments_apis_part.yml --outfile build/swagger/payments/doc/${VERSION}.json --type=json


      ##- run: ./build-dictionary.sh
      ##- run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' source/swagger/swagger_*

      # Open Banking Fase 2
      - run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' build/swaggers/accounts/doc/*.json
      - run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' build/swaggers/consents/doc/*.json
      - run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' build/swaggers/credit_cards/doc/*.json
      - run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' build/swaggers/customers/doc/*.json
      - run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' build/swaggers/financings/doc/*.json
      - run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' build/swaggers/invoice_financings/doc/*.json
      - run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' build/swaggers/loans/doc/*.json
      - run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' build/swaggers/resources/doc/*.json
      - run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' build/swaggers/unarranged_accounts_overdraft/doc/*.json

      # Open Banking Fase 3
      - run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' build/swaggers/payments/doc/*.json

      # Validations
      # Open Banking Fase 2
      - run: swagger-cli validate build/swaggers/accounts/doc/*.json
      - run: swagger-cli validate build/swaggers/consents/doc/*.json
      - run: swagger-cli validate build/swaggers/credit_cards/doc/*.json
      - run: swagger-cli validate build/swaggers/customers/doc/*.json
      - run: swagger-cli validate build/swaggers/financings/doc/*.json
      - run: swagger-cli validate build/swaggers/invoice_financings/doc/*.json
      - run: swagger-cli validate build/swaggers/loans/doc/*.json
      - run: swagger-cli validate build/swaggers/resources/doc/*.json
      - run: swagger-cli validate build/swaggers/unarranged_accounts_overdraft/doc/*.json
      
      # Open Banking Fase 3
      - run: swagger-cli validate build/swaggers/payments/doc/*.json


      #- uses: actions/cache@v1
      #  with:
      #    path: build
      #    key: ${{ runner.os }}-${{ hashFiles('**/source') }}


      # Run Spectral
      - uses: stoplightio/spectral-action@v0.7.0
        with:
          file_glob: 'documentation/build/swagger/*.*'