name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Github pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: documentation
    #env:
    #  ruby-version: 2.5

    

    steps:

      - run: pwd
      - run: ls -la

      #- uses: actions/cache@v1
      #  with:
      #    path: source/swaggers
      #    key: ${{ runner.os }}-${{ hashFiles('**/source') }}
#
      #- run: bundle config set deployment 'true'
      #- run: bundle install
      #- run: bundle exec middleman build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/source/swaggers


