name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Github pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: documentation
    #env:
    #  ruby-version: 2.5

    steps:

      - uses: actions/cache@v1
        with:
          path: source/swaggers
          key: ${{ runner.os }}-${{ hashFiles('**/source') }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/swaggers
